// Code generated by gen_gosys.go using 'go generate'. DO NOT EDIT.

//go:build hurd
package gosys

const GOOS = `hurd`

const IsAix = false
const IsAndroid = false
const IsDarwin = false
const IsDragonfly = false
const IsFreebsd = false
const IsHurd = true
const IsIllumos = false
const IsIos = false
const IsJs = false
const IsLinux = false
const IsNetbsd = false
const IsOpenbsd = false
const IsPlan9 = false
const IsSolaris = false
const IsWindows = false
const IsZos = false
