// Code generated by gen_gosys.go using 'go generate'. DO NOT EDIT.

//go:build !android && linux
package gosys

const GOOS = `linux`

const IsAix = false
const IsAndroid = false
const IsDarwin = false
const IsDragonfly = false
const IsFreebsd = false
const IsHurd = false
const IsIllumos = false
const IsIos = false
const IsJs = false
const IsLinux = true
const IsNetbsd = false
const IsOpenbsd = false
const IsPlan9 = false
const IsSolaris = false
const IsWindows = false
const IsZos = false
